---
title: "Presentation 2"
author: "Owen Gallagher"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(reshape2)
```

# CPI Data

```{r}
setwd('~/Important/Stat_633_Data_Viz/Presentation_2/Debt_Project/')

# Read data in
housing.cpi <- read.csv('CPI_Housing_Final.csv')
all.items.cpi <- read.csv('CPI_All_Items.csv')
education.cpi <- read.csv('CPI_Education_Final.csv')
used.cars.cpi <- read.csv('CPI_Used_Cars.csv', col.names = c('Year', 'Q1.Used', 'Q2.Used', 'Q3.Used', 'Q4.Used'))
new.cars.cpi <- read.csv('New_Cars_CPI.csv',col.names = c('Year', 'Q1.New', 'Q2.New', 'Q3.New', 'Q4.New'))
car.sales <- read.csv('cars_sales.csv')

# Select only relevant parts
car.sales <- car.sales %>% select(Year, Percent.New, Percent.Used)

# Melt data so that CPI data is in same form as the debt data
housing.cpi <- melt(housing.cpi, id.vars = 'Year', variable.name = 'Quarter', value.name = 'Housing.CPI') %>% arrange(Year)
all.items.cpi <- melt(all.items.cpi, id.vars = 'Year', variable.name = 'Quarter', value.name = 'All.Items.CPI') %>% arrange(Year)
education.cpi <- melt(education.cpi, id.vars = 'Year', variable.name = 'Quarter', value.name = 'Education.CPI') %>% arrange(Year)

#Join all car data
cars.cpi.draft <- used.cars.cpi %>%
    left_join(new.cars.cpi, join_by(Year == Year)) %>%
    left_join(car.sales, join_by(Year == Year))

# Created a weighted average CPI
cars.cpi <- cars.cpi.draft %>%
    mutate(Q1 = Q1.Used * Percent.Used + Q1.New * Percent.New,
           Q2 = Q2.Used * Percent.Used + Q2.New * Percent.New,
           Q3 = Q3.Used * Percent.Used + Q3.New * Percent.New,
           Q4 = Q4.Used * Percent.Used + Q4.New * Percent.New) %>%
    select(Year, Q1, Q2, Q3, Q4) %>%
    melt(id.vars = 'Year', variable.name = 'Quarter', value.name = 'Auto.CPI') %>% arrange(Year)



# Join all the cpi into one dataset
cpi.data <- housing.cpi %>%
    left_join(all.items.cpi, by = join_by(Year == Year, Quarter == Quarter)) %>% 
    left_join(education.cpi, by = join_by(Year == Year, Quarter == Quarter)) %>%
    left_join(cars.cpi, by = join_by(Year == Year, Quarter == Quarter))

#Cut off 2024 where there is no data
cpi.data <- cpi.data[1:84,]

tail(cpi.data)
```

# Read in Total Debt

```{r}
setwd('~/Important/Stat_633_Data_Viz/Presentation_2/Debt_Project/')

unadjusted.debt <- read.csv('total_debt.csv')

debt.with.cpi <- unadjusted.debt %>%
    left_join(cpi.data, by = join_by(Year == Year, Quarter == Quarter))

head(debt.with.cpi)
```

# Adjust for inflation

```{r}
adjusted.debt <- debt.with.cpi %>%
    mutate(
        Mortgage = (Mortgage / Housing.CPI) * 100,
        HE.Revolving = (HE.Revolving / Housing.CPI) * 100,
        Auto.Loan = (Auto.Loan / Auto.CPI) * 100,
        Student.Loan = (Student.Loan / Education.CPI) * 100,
        Credit.Card = (Credit.Card / All.Items.CPI) * 100,
        Other = (Other / All.Items.CPI) * 100,
        Total = Mortgage + HE.Revolving + Auto.Loan + Credit.Card + Other
    ) %>%
    select(-(Housing.CPI:Auto.CPI))

head(adjusted.debt)
```

## Include Rates

```{r}
auto.rates <- read.csv('auto_rates.csv')
mortgage.rates <- read.csv('mortgage_rates.csv')
credit.card.rates <- read.csv('credit_card_rates.csv')
student.loans <- read.csv('student_loans.csv')

rates <- mortgage.rates %>%
    left_join(auto.rates, join_by(Year == Year, Quarter == Quarter)) %>%
    left_join(credit.card.rates, join_by(Year == Year, Quarter == Quarter)) %>%
    left_join(student.loans, join_by(Year == Year, Quarter == Quarter)) %>%
    mutate(Mortgage.Rate = round(Mortgage.Rate,2))

head(rates)
```


## Make Final Dataframe
```{r}

salary <- read.csv('Salary.csv')

final.df <- adjusted.debt %>%
    left_join(salary, by = join_by(Year == Year)) %>%
    left_join(rates, by = join_by(Year == Year, Quarter == Quarter)) %>%
    mutate(Year.Quarter = paste(Year, Quarter))
```


## Plots

```{r}
library(plotly)

y.axis.2 <- list(
    overlaying = 'y',
    side = 'right',
    title = 'Salary Axis'
)

plot_ly(data = final.df) %>%
    add_lines(
              x = ~Year.Quarter, 
              y = ~Mortgage,
              name = 'Mortgage') %>%
    add_lines(
              x = ~Year.Quarter, 
              y = ~Auto.Loan,
              name = 'Auto Loans') %>%
    add_lines(x = ~Year.Quarter,
              y =~Salary,
              name = 'Salary',
              yaxis = 'y2') %>%
    add_lines(x = ~Year.Quarter,
              y =~Student.Loan,
              name = 'Student Loans') %>%
    add_lines(x = ~Year.Quarter,
              y =~Credit.Card,
              name = 'Credit Cards') %>%
    layout(
        yaxis2 = y.axis.2
    )
```


```{r}
plot_ly(data = final.df) %>%
    add_lines(
        x =~Year.Quarter,
        y = ~CC.Delinquency.30.days.late.Percent,
        name = '30 days late'
    ) %>%
    add_lines(
        x =~Year.Quarter,
        y = ~CC.Delinquency.60.days.late.Percent,
        name = '60 days late'
    ) %>%
    add_lines(
        x =~Year.Quarter,
        y = ~CC.Delinquency.90.days.late.Percent,
        name = '90 days late'
    ) %>%
    add_lines(
        x =~Year.Quarter,
        y = ~CC.Delinquency.120.or.moredays.late.Percent,
        name = '120 days or more'
    )
```



## Panel View

```{r}

mortgage.plot <- plot_ly(final.df) %>%
    add_lines(x = ~Year.Quarter,
              y = ~Percent.of.Mortgage.90.days.delinquent,
              color = I('blue'),
              text = ~paste('Type: Mortgage', '<br>',
                            'Year:', Year, '<br>',
                           'Quarter:', Quarter, '<br>',
                           '90 Days Delinquent (%):', Percent.of.Mortgage.90.days.delinquent),
              hoverinfo = 'text',
              legendgroup = 'Percent 90 days delinquent',
              name = 'Percent 90 days delinquent') %>%
    add_lines(x = ~Year.Quarter,
              y = ~Mortgage.Rate,
              color = I('orange'),
              text = ~paste('Type: Mortgage <br>',
                            'Year:', Year, '<br>',
                           'Quarter:', Quarter, '<br>',
                           'Mortgage Rate:', Mortgage.Rate),
              hoverinfo = 'text',
              name = 'Mortgage Rate') %>%
    layout(
        yaxis = list(title = 'Percent'),
        xaxis = list(
            title = 'Year',
            ticktext = list('2003', '2005' ,'2007', '2009', '2011', '2013', '2015', '2017', '2019', '2021', '2023'),
            tickvals = list('2003 Q1', '2005 Q1' ,'2007 Q1', '2009 Q1', '2011 Q1', '2013 Q1', '2015 Q1', '2017 Q1', '2019 Q1', '2021 Q1', '2023 Q1')
        )
    )

mortgage.plot
```


```{r}
auto.plot <- plot_ly(final.df) %>%
    add_lines(x = ~Year.Quarter,
              y = ~Percent.of.Auto.90.days.delinquent,
              color = I('blue'),
              text = ~paste('Type: Auto <br>',
                            'Year', Year, '<br>',
                           'Quarter', Quarter, '<br>',
                           '90 Days Delinquent (%)', Percent.of.Auto.90.days.delinquent),
              hoverinfo = 'text',
              name = 'Percent 90 days delinquent',
              legendgroup = 'Percent 90 days delinquent',
              showlegend = FALSE) %>%
    add_lines(x = ~Year.Quarter,
              y = ~Auto.Rates.48.mo,
              color = I('red'),
              text = ~paste('Type: Auto <br>',
                            'Year:', Year, '<br>',
                           'Quarter:', Quarter, '<br>',
                           'Auto Rate:', Auto.Rates.48.mo),
              hoverinfo = 'text',
              name = 'Auto Rate') %>%
    layout(
        yaxis = list(title = 'Percent'),
        xaxis = list(
            title = 'Year',
            ticktext = list('2003', '2005' ,'2007', '2009', '2011', '2013', '2015', '2017', '2019', '2021', '2023'),
            tickvals = list('2003 Q1', '2005 Q1' ,'2007 Q1', '2009 Q1', '2011 Q1', '2013 Q1', '2015 Q1', '2017 Q1', '2019 Q1', '2021 Q1', '2023 Q1')
        )
    )


auto.plot
```


```{r}
student.loan.plot <- plot_ly(final.df) %>%
    add_lines(x = ~Year.Quarter,
              y = ~Percent.of.Student.Loan.90.days.delinquent,
              color = I('blue'),
              text = ~paste('Type: Student Loan <br>',
                            'Year:', Year, '<br>',
                           'Quarter:', Quarter, '<br>',
                           '90 Days Delinquent (%):', Percent.of.Student.Loan.90.days.delinquent),
              hoverinfo = 'text',
              legendgroup = 'Percent 90 days delinquent',
              showlegend = FALSE,
              name = 'Percent 90 days delinquent') %>%
    add_lines(x = ~Year.Quarter,
              y = ~Student.Loan.Rate,
              color = I('purple'),
              text = ~paste('Type: Student Loan <br>',
                            'Year:', Year, '<br>',
                           'Quarter:', Quarter, '<br>',
                           'Student Loan Rate:', Student.Loan.Rate),
              hoverinfo = 'text',
              name = 'Student Loan Rate') %>%
    layout(
        yaxis = list(title = 'Percent'),
        xaxis = list(
            title = 'Year',
            ticktext = list('2003', '2005' ,'2007', '2009', '2011', '2013', '2015', '2017', '2019', '2021', '2023'),
            tickvals = list('2003 Q1', '2005 Q1' ,'2007 Q1', '2009 Q1', '2011 Q1', '2013 Q1', '2015 Q1', '2017 Q1', '2019 Q1', '2021 Q1', '2023 Q1')
        )
    )

student.loan.plot
```


```{r}
credit.card.plot <- plot_ly(final.df) %>%
    add_lines(x = ~Year.Quarter,
              y = ~Percent.of.CC.90.days.delinquent,
              color = I('blue'),
              text = ~paste('Type: Credit Card <br>',
                            'Year:', Year, '<br>',
                           'Quarter:', Quarter, '<br>',
                           '90 Days Delinquent (%):', Percent.of.CC.90.days.delinquent),
              hoverinfo = 'text',
              legendgroup = 'Percent 90 days delinquent',
              showlegend = FALSE,
              name = 'Percent 90 days delinquent') %>%
    add_lines(x = ~Year.Quarter,
              y = ~CC.Rates,
              color = I('darkgreen'),
              text = ~paste('Type: Credit Card <br>',
                            'Year:', Year, '<br>',
                           'Quarter:', Quarter, '<br>',
                           'Credit Card Rate:', CC.Rates),
              hoverinfo = 'text',
              name = 'Credit Card Rate') %>%
    layout(
        yaxis = list(title = 'Percent'),
        xaxis = list(
            title = 'Year',
            ticktext = list('2003', '2005' ,'2007', '2009', '2011', '2013', '2015', '2017', '2019', '2021', '2023'),
            tickvals = list('2003 Q1', '2005 Q1' ,'2007 Q1', '2009 Q1', '2011 Q1', '2013 Q1', '2015 Q1', '2017 Q1', '2019 Q1', '2021 Q1', '2023 Q1')
        )
    )

credit.card.plot
```


```{r}
delinq.plot <- subplot(mortgage.plot, credit.card.plot, auto.plot, student.loan.plot, nrows = 4, shareX = T, margin = 0.01, heights = c(.25,.25,.25,.25), widths = .75)

annotations = list( 

  list( 

    x = 0,  

    y = .85,  

    text = "Mortgage Plot",  

    xref = "paper",  

    yref = "paper",  

    xanchor = "center",  

    yanchor = "bottom",  

    showarrow = FALSE 

  ),  

  list( 

    x = 0,  

    y = .6,  

    text = "Credit Card Plot",  

    xref = "paper",  

    yref = "paper",  

    xanchor = "center",  

    yanchor = "bottom",  

    showarrow = FALSE 

  ),  

  list( 

    x = 0,  

    y = 0.33,  

    text = "Auto Plot",  

    xref = "paper",  

    yref = "paper",  

    xanchor = "center",  

    yanchor = "bottom",  

    showarrow = FALSE 

  ),

  list( 

    x = 0,  

    y = 0.075,  

    text = "Student Loan Plot",  

    xref = "paper",  

    yref = "paper",  

    xanchor = "center",  

    yanchor = "bottom",  

    showarrow = FALSE 

  ))


delinq.plot <- delinq.plot %>%layout(annotations = annotations) 
delinq.plot
```

